apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "proglog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "proglog.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "proglog.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "proglog.fullname" . }}
      labels: {{ include "proglog.labels" . | nindent 8 }}
    spec:
      # initContainers...
      initContainers:
      - name: {{ include "proglog.fullname" . }}-config-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |-
            rm -r /var/run/proglog/data
            mkdir -p /var/run/proglog/data
            ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
            cat > /var/run/proglog/config.yaml <<EOD
            data-dir: /var/run/proglog/data
            rpc-port: {{.Values.rpcPort}}
            bind-addr: "$HOSTNAME.proglog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"
            $([ $ID != 0 ] && echo 'start-join-addrs: "proglog-0.proglog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"')
            bootstrap: $([ $ID = 0 ] && echo true || echo false)
            $([ $ID = 0 ] && echo 'server-tls-cert-file: /usr/local/.proglog/server.pem')
            $([ $ID = 0 ] && echo 'server-tls-key-file: /usr/local/.proglog/server-key.pem')
            $([ $ID = 0 ] && echo 'server-tls-ca-file: /usr/local/.proglog/ca.pem')
            $([ $ID != 0 ] && echo 'peer-tls-cert-file: /usr/local/.proglog/root-client.pem')
            $([ $ID != 0 ] && echo 'peer-tls-key-file: /usr/local/.proglog/root-client-key.pem')
            $([ $ID != 0 ] && echo 'peer-tls-ca-file: /usr/local/.proglog/ca.pem')
            acl-model-file: /usr/local/.proglog/model.conf
            acl-policy-file: /usr/local/.proglog/policy.csv
            EOD
        volumeMounts:
        - name: datadir
          mountPath: /var/run/proglog
      # containers...
      containers:
      - name: {{ include "proglog.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.rpcPort }}
          name: rpc
        - containerPort: {{ .Values.serfPort }}
          name: serf
        args:
          - --config-file=/var/run/proglog/config.yaml
        # probes...
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
        #   initialDelaySeconds: 10
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
        #   initialDelaySeconds: 10
        volumeMounts:
        - name: datadir
          mountPath: /var/run/proglog
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}